apiVersion: 1

datasources:
  - uid: influxdb-uid
    name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    jsonData:
      version: Flux
      organization: rocket
      defaultBucket: mock_data
    secureJsonData:
      token: my-super-token
    isDefault: true
